OPENAI_ORG = 'org-oESkQmawNDmDfpRhUKQsnA6R'
OPENAI_API_KEY = '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'
GOOGLE_KEY = 'AIzaSyA3qBZVvORUdvgFkjfVhDqVP4qKRmnaAXk'


[gcp_service_account]
type = "service_account"
project_id = "lucky-rookery-102815"
private_key_id = "46bc4e8b7a99609a71b217b10d0d11fdec55d469"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCem4auIf+XT1J1
PK0Iw+dn8A4ft+AnZ/sMWTULYL2RMOYNYBwaoQowcFT2mRavndz4SAKRGrgQ376C
/P5Xc+3JjkLeauBMM5Vrs1rU2X0kUfGs3VQftO5CPTOB6ScPDZI3IlPiQZkWiKE2
joxeO1NL0AnTKHc3+7lcB8iMxfVCYGxLbYms+pMKE4ktqT2ITaJx9Sgu0Iua1N4W
1gGxCGf7QjWI89/ElXQiDJED53ka6ew80lXvCmw3IP2mT05lRsEy35rOcXXa+H6R
2W8v4Wy6fjGookVYdq5LvzXHSav72u4usVJNwtDSjUpmuhlR6eQ8+TL2IGjAwj78
CUWXvUQRAgMBAAECggEAGmg7lr97XhZrXLCjAJwZaaE6wMYtEHKMBmTN45ySQ1u4
Wc7ALyDT4Pe69anMcKXgdggLQVyI++o8vnNf53CaTR4d/QkfWiCWhq2AeILThpoM
GmNpT7QgnS+yZTVL9wIj74EMJVYVpn5OFRbLwR6wgiVblWgd3VjQZkW3etS0vn2r
OUX02wAY2ykmmx161mPbBN5ffuCPsiicdLJLqjVOVSP20HUnD4sufCsNmGcMXhsG
t41u7JKjUBSVAReUEz46wrT+UdxdRLH+kdJNrP5+uyKPH/5ADMzWhFJ4dQkba94D
GoRK4tk9+4/kkQCiI/Iudwba+uPh/kJBjJiTgwYUJwKBgQDPkNb89/qrxDLCreM4
E6Ti+EYHj6PA0M0ooBnk87dE1dKw/LE8FpkKkcA52ju1NldKL6YNjJfsNChTiwMG
jDDu1XIFGui+dxTQbCBBW0TNCPADOzR+ATL4xtyPYNRc6JasBCFDwu/JHS1qomiT
gGcT+UaOYvXM9sOS210fjgJmmwKBgQDDnh0EIINTh6nzjPf1z1hS+PEUso2Fqp6l
R6dIHqXJDi2mlKMHzALREUne73ir5l69iOTCznNk7pL0+tlKv+pn+vdKlL+N97DJ
POsC45aEvrjjC2LeOfO1rfd6LNjYYltbYv1ywTR+OpF6+pGFtgGvAL4yjtpNeKXj
Cu60z38UwwKBgQCLPaK7OK9UIt3ac0QGDkeCawKvd9BmPKwkIKK+UDAVYUthp2JN
6OrpiDTnmlqLidSs06IVXMddkO+se4igD9OTpGREwHR5sPCpkJ9iuJNC6Ef6IvFn
xe4nrV+wX0iWuwC4jFy0VET/KS+aZTC6Il0DrSmDwycZRECWd8nUrTM3GQKBgF6z
OdrYnpsejzEf6p6ufVTVvWhGtGqkWd8r3Bj29U1rNsBxLqfEpQxvcTKi/elCQlVB
Y3XHmmefc7dzhSRB2onyHiuV7VIeOhCCFEe2xBSJfFo2Fev9ZDVs/eTAt02x+AY6
2vXmALKnSeyeRzrTDOea1XkGXTqqEKzkiwEvfpcfAoGADMv8cn3fVLVbpAcfNUHi
9iVE0PEOQehLnphee8rTmFHdpGCZqbHepy/9EKeBs5TLyBW/Pmj2VCLUchHDAXNY
Ce43R4AhtT2BA/QuxSgeYo2bSuG5GBmz2yl29AqwuGhlQELVpz/lYitAbZOzDyJ1
Exl4x4+q8qmj4ghOp0KLZL4=
-----END PRIVATE KEY-----
"""
client_email = "lucky-rookery-102815@appspot.gserviceaccount.com"
client_id = ""
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/lucky-rookery-102815%40appspot.gserviceaccount.com"
